### ISSUE TITLE
Update Notification Documentation

### ISSUE THREAD

**Issue by pootsbook** [socialpaymentsbv/docs.clubcollect.com#4]
From https://docs.clubcollect.com/api-documentation/notifications

> Notifications are sent out on a regular basis every ten minutes.

This is no longer true. Update documentation to reflect:

1. “real-time” updates
2. new JSON payload format
3. `GET /invoices` / `GET /invoice_lines` is explicitly mentioned as the way to fetch data after receiving a notification

**Comment by prwater** [comment]
* Is this change already in production? If so, please update the documentation to reflect the new 
payload format.
* What happens if the endpoint of Partner does not responds with a 200 status code? For example, due a network timeout, or an update being installed. Will ClubCollect try later again to deliver the payload?

**Comment by vruizext** [comment]
@prwater thanks for reporting this. 

The real-time notifications are live. They can be enabled upon request.

These notifications have the same format as the notifications sent in batches, to allow partner to handle both types with a single endpoint. 

When we don't receive a 200 OK for any notification, the notification is added to the next batch of asynchronous notifications. 

Details will be added to docs soon, see #30
